### ISSUE TITLE
Non-ASCII character Issue in pam.py

### ISSUE THREAD

**Issue by jcmerg** [HelgeKeck/pam#20]
File "/home/pi/klipper/klippy/extras/pam.py", line 107
SyntaxError: Non-ASCII character '\xc3' in file /home/pi/klipper/klippy/extras/pam.py on line 107, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

FIX: Replacing geman "umlauts" in line 107

**Comment by HelgeKeck** [comment]
fixed
